# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/efficientdet_tf1/proto/aug_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<nvidia_tao_deploy/cv/efficientdet_tf1/proto/aug_config.proto\"]\n\tAugConfig\x12\x12\n\nrand_hflip\x18\x01 \x01(\x08\x12\x1d\n\x15random_crop_min_scale\x18\x02 \x01(\x02\x12\x1d\n\x15random_crop_max_scale\x18\x03 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.efficientdet_tf1.proto.aug_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUGCONFIG._serialized_start=64
  _AUGCONFIG._serialized_end=157
# @@protoc_insertion_point(module_scope)
