# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/efficientdet_tf1/proto/training_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAnvidia_tao_deploy/cv/efficientdet_tf1/proto/training_config.proto\"\xf9\x04\n\x0eTrainingConfig\x12\x18\n\x10train_batch_size\x18\x01 \x01(\r\x12\x1b\n\x13iterations_per_loop\x18\x02 \x01(\r\x12\x0f\n\x07use_xla\x18\x03 \x01(\x08\x12\x17\n\x0f\x64isable_logging\x18\x04 \x01(\x08\x12\x12\n\ncheckpoint\x18\x05 \x01(\t\x12\x15\n\rstop_at_epoch\x18\x06 \x01(\r\x12\x0e\n\x06resume\x18\x07 \x01(\x08\x12\x19\n\x11\x63heckpoint_period\x18\x08 \x01(\r\x12\x1b\n\x13keep_checkpoint_max\x18\t \x01(\r\x12\x1e\n\x16num_examples_per_epoch\x18\n \x01(\r\x12\x12\n\nnum_epochs\x18\x0b \x01(\r\x12!\n\x19skip_checkpoint_variables\x18\x0c \x01(\t\x12\x1a\n\x12profile_skip_steps\x18\r \x01(\r\x12\x16\n\x0etf_random_seed\x18\x0e \x01(\r\x12\x1c\n\x14moving_average_decay\x18\x0f \x01(\x02\x12\x17\n\x0flr_warmup_epoch\x18\x10 \x01(\x02\x12\x16\n\x0elr_warmup_init\x18\x11 \x01(\x02\x12\x15\n\rlearning_rate\x18\x12 \x01(\x02\x12\x0b\n\x03\x61mp\x18\x13 \x01(\x08\x12\x17\n\x0fl2_weight_decay\x18\x14 \x01(\x02\x12\x17\n\x0fl1_weight_decay\x18\x15 \x01(\x02\x12\x19\n\x11pruned_model_path\x18\x16 \x01(\t\x12\x1b\n\x13\x63lip_gradients_norm\x18\x17 \x01(\x02\x12\x10\n\x08momentum\x18\x18 \x01(\x02\x12\x19\n\x11logging_frequency\x18\x19 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.efficientdet_tf1.proto.training_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAININGCONFIG._serialized_start=70
  _TRAININGCONFIG._serialized_end=703
# @@protoc_insertion_point(module_scope)
