# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/efficientdet_tf1/proto/training_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nvidia_tao_deploy/cv/efficientdet_tf1/proto/training_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nAnvidia_tao_deploy/cv/efficientdet_tf1/proto/training_config.proto\"\xf9\x04\n\x0eTrainingConfig\x12\x18\n\x10train_batch_size\x18\x01 \x01(\r\x12\x1b\n\x13iterations_per_loop\x18\x02 \x01(\r\x12\x0f\n\x07use_xla\x18\x03 \x01(\x08\x12\x17\n\x0f\x64isable_logging\x18\x04 \x01(\x08\x12\x12\n\ncheckpoint\x18\x05 \x01(\t\x12\x15\n\rstop_at_epoch\x18\x06 \x01(\r\x12\x0e\n\x06resume\x18\x07 \x01(\x08\x12\x19\n\x11\x63heckpoint_period\x18\x08 \x01(\r\x12\x1b\n\x13keep_checkpoint_max\x18\t \x01(\r\x12\x1e\n\x16num_examples_per_epoch\x18\n \x01(\r\x12\x12\n\nnum_epochs\x18\x0b \x01(\r\x12!\n\x19skip_checkpoint_variables\x18\x0c \x01(\t\x12\x1a\n\x12profile_skip_steps\x18\r \x01(\r\x12\x16\n\x0etf_random_seed\x18\x0e \x01(\r\x12\x1c\n\x14moving_average_decay\x18\x0f \x01(\x02\x12\x17\n\x0flr_warmup_epoch\x18\x10 \x01(\x02\x12\x16\n\x0elr_warmup_init\x18\x11 \x01(\x02\x12\x15\n\rlearning_rate\x18\x12 \x01(\x02\x12\x0b\n\x03\x61mp\x18\x13 \x01(\x08\x12\x17\n\x0fl2_weight_decay\x18\x14 \x01(\x02\x12\x17\n\x0fl1_weight_decay\x18\x15 \x01(\x02\x12\x19\n\x11pruned_model_path\x18\x16 \x01(\t\x12\x1b\n\x13\x63lip_gradients_norm\x18\x17 \x01(\x02\x12\x10\n\x08momentum\x18\x18 \x01(\x02\x12\x19\n\x11logging_frequency\x18\x19 \x01(\rb\x06proto3')
)




_TRAININGCONFIG = _descriptor.Descriptor(
  name='TrainingConfig',
  full_name='TrainingConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_batch_size', full_name='TrainingConfig.train_batch_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iterations_per_loop', full_name='TrainingConfig.iterations_per_loop', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_xla', full_name='TrainingConfig.use_xla', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disable_logging', full_name='TrainingConfig.disable_logging', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpoint', full_name='TrainingConfig.checkpoint', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_at_epoch', full_name='TrainingConfig.stop_at_epoch', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resume', full_name='TrainingConfig.resume', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpoint_period', full_name='TrainingConfig.checkpoint_period', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keep_checkpoint_max', full_name='TrainingConfig.keep_checkpoint_max', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_examples_per_epoch', full_name='TrainingConfig.num_examples_per_epoch', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_epochs', full_name='TrainingConfig.num_epochs', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skip_checkpoint_variables', full_name='TrainingConfig.skip_checkpoint_variables', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile_skip_steps', full_name='TrainingConfig.profile_skip_steps', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tf_random_seed', full_name='TrainingConfig.tf_random_seed', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moving_average_decay', full_name='TrainingConfig.moving_average_decay', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lr_warmup_epoch', full_name='TrainingConfig.lr_warmup_epoch', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lr_warmup_init', full_name='TrainingConfig.lr_warmup_init', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='TrainingConfig.learning_rate', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amp', full_name='TrainingConfig.amp', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l2_weight_decay', full_name='TrainingConfig.l2_weight_decay', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l1_weight_decay', full_name='TrainingConfig.l1_weight_decay', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pruned_model_path', full_name='TrainingConfig.pruned_model_path', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clip_gradients_norm', full_name='TrainingConfig.clip_gradients_norm', index=22,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='TrainingConfig.momentum', index=23,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logging_frequency', full_name='TrainingConfig.logging_frequency', index=24,
      number=25, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=703,
)

DESCRIPTOR.message_types_by_name['TrainingConfig'] = _TRAININGCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainingConfig = _reflection.GeneratedProtocolMessageType('TrainingConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAININGCONFIG,
  __module__ = 'nvidia_tao_deploy.cv.efficientdet_tf1.proto.training_config_pb2'
  # @@protoc_insertion_point(class_scope:TrainingConfig)
  ))
_sym_db.RegisterMessage(TrainingConfig)


# @@protoc_insertion_point(module_scope)
