# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/unet/proto/data_class_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nvidia_tao_deploy/cv/unet/proto/data_class_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n7nvidia_tao_deploy/cv/unet/proto/data_class_config.proto\"\xa3\x01\n\x0f\x44\x61taClassConfig\x12\x34\n\x0etarget_classes\x18\x01 \x03(\x0b\x32\x1c.DataClassConfig.TargetClass\x1aZ\n\x0bTargetClass\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x63lass_weight\x18\x02 \x01(\x02\x12\x10\n\x08label_id\x18\x03 \x01(\x05\x12\x15\n\rmapping_class\x18\x04 \x01(\tb\x06proto3')
)




_DATACLASSCONFIG_TARGETCLASS = _descriptor.Descriptor(
  name='TargetClass',
  full_name='DataClassConfig.TargetClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DataClassConfig.TargetClass.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_weight', full_name='DataClassConfig.TargetClass.class_weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_id', full_name='DataClassConfig.TargetClass.label_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapping_class', full_name='DataClassConfig.TargetClass.mapping_class', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=223,
)

_DATACLASSCONFIG = _descriptor.Descriptor(
  name='DataClassConfig',
  full_name='DataClassConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_classes', full_name='DataClassConfig.target_classes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATACLASSCONFIG_TARGETCLASS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=223,
)

_DATACLASSCONFIG_TARGETCLASS.containing_type = _DATACLASSCONFIG
_DATACLASSCONFIG.fields_by_name['target_classes'].message_type = _DATACLASSCONFIG_TARGETCLASS
DESCRIPTOR.message_types_by_name['DataClassConfig'] = _DATACLASSCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataClassConfig = _reflection.GeneratedProtocolMessageType('DataClassConfig', (_message.Message,), dict(

  TargetClass = _reflection.GeneratedProtocolMessageType('TargetClass', (_message.Message,), dict(
    DESCRIPTOR = _DATACLASSCONFIG_TARGETCLASS,
    __module__ = 'nvidia_tao_deploy.cv.unet.proto.data_class_config_pb2'
    # @@protoc_insertion_point(class_scope:DataClassConfig.TargetClass)
    ))
  ,
  DESCRIPTOR = _DATACLASSCONFIG,
  __module__ = 'nvidia_tao_deploy.cv.unet.proto.data_class_config_pb2'
  # @@protoc_insertion_point(class_scope:DataClassConfig)
  ))
_sym_db.RegisterMessage(DataClassConfig)
_sym_db.RegisterMessage(DataClassConfig.TargetClass)


# @@protoc_insertion_point(module_scope)
