model_name: null
encryption_key: null
results_dir: /results
wandb:
  enable: true
  project: TAO Toolkit
  entity: ''
  tags:
  - training
  - tao-toolkit
  reinit: false
  sync_tensorboard: false
  save_code: false
  name: TAO Toolkit training experiment
  run_id: ''
model:
  pretrained_backbone_path: null
  backbone: resnet_50
  train_backbone: true
  load_teacher_enc_dec: false
  num_queries: 300
  num_select: 300
  num_feature_levels: 3
  return_interm_indices:
  - 1
  - 2
  - 3
  feat_strides:
  - 8
  - 16
  - 32
  feat_channels:
  - 256
  - 256
  - 256
  use_encoder_idx:
  - 2
  hidden_dim: 256
  nheads: 8
  dropout_ratio: 0.0
  enc_layers: 1
  dim_feedforward: 1024
  pe_temperature: 10000
  expansion: 1.0
  depth_mult: 1
  enc_act: gelu
  act: silu
  dec_layers: 6
  dn_number: 100
  eval_idx: -1
  vfl_loss_coef: 1.0
  bbox_loss_coef: 5.0
  giou_loss_coef: 2.0
  class_cost: 2.0
  bbox_cost: 5.0
  giou_cost: 2.0
  alpha: 0.75
  gamma: 2.0
  clip_max_norm: 0.1
  aux_loss: true
  loss_types:
  - vfl
  - boxes
  backbone_names:
  - backbone.0
  linear_proj_names:
  - reference_points
  - sampling_offsets
  distillation_loss_coef: 1.0
  frozen_fm:
    enabled: false
    backbone: radio_v2-l
    checkpoint: null
dataset:
  train_data_sources: null
  val_data_sources: null
  test_data_sources: null
  infer_data_sources: null
  quant_calibration_data_sources: null
  batch_size: 4
  workers: 8
  remap_mscoco_category: false
  pin_memory: true
  dataset_type: serialized
  num_classes: 80
  eval_class_ids: null
  augmentation:
    multi_scales:
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800
    train_spatial_size:
    - 640
    - 640
    eval_spatial_size:
    - 640
    - 640
    distortion_prob: 0.8
    iou_crop_prob: 0.8
    preserve_aspect_ratio: false
train:
  num_gpus: 1
  gpu_ids:
  - 0
  num_nodes: 1
  seed: 1234
  cudnn:
    benchmark: false
    deterministic: true
  num_epochs: 10
  checkpoint_interval: 1
  checkpoint_interval_unit: epoch
  validation_interval: 1
  resume_training_checkpoint_path: null
  results_dir: null
  freeze: []
  pretrained_model_path: null
  clip_grad_norm: 0.1
  is_dry_run: false
  enable_ema: false
  ema:
    decay: 0.999
    every_n_steps: 1
    validate_original_weights: false
    cpu_offload: false
  optim:
    optimizer: AdamW
    monitor_name: val_loss
    lr: 0.0001
    lr_backbone: 1.0e-05
    momentum: 0.9
    weight_decay: 0.0001
    lr_scheduler: MultiStep
    lr_steps:
    - 1000
    lr_step_size: 1000
    lr_decay: 0.1
    warmup_steps: 0
  precision: fp32
  distributed_strategy: ddp
  activation_checkpoint: true
evaluate:
  num_gpus: 1
  gpu_ids:
  - 0
  num_nodes: 1
  checkpoint: ???
  trt_engine: null
  results_dir: null
  batch_size: -1
  input_width: null
  input_height: null
  conf_threshold: 0.0
  is_quantized: false
inference:
  num_gpus: 1
  gpu_ids:
  - 0
  num_nodes: 1
  checkpoint: ???
  trt_engine: null
  results_dir: null
  batch_size: -1
  color_map: null
  conf_threshold: 0.5
  is_internal: false
  input_width: null
  input_height: null
  outline_width: 3
  is_quantized: false
export:
  results_dir: null
  gpu_id: 0
  checkpoint: ???
  onnx_file: ???
  on_cpu: false
  input_channel: 3
  input_width: 640
  input_height: 640
  opset_version: 17
  batch_size: -1
  verbose: false
  format: onnx
  serialize_nvdsinfer: false
  is_quantized: false
gen_trt_engine:
  results_dir: null
  gpu_id: 0
  onnx_file: ???
  trt_engine: ???
  timing_cache: null
  batch_size: -1
  verbose: false
  tensorrt:
    workspace_size: 1024
    min_batch_size: 1
    opt_batch_size: 1
    max_batch_size: 4
    layers_precision: []
    data_type: FP32
    calibration:
      cal_image_dir: ???
      cal_cache_file: ???
      cal_batch_size: 1
      cal_batches: 1
distill: null
quantize:
  backend: torchao
  mode: weight_only_ptq
  algorithm: minmax
  default_layer_dtype: native
  default_activation_dtype: native
  layers: []
  skip_names: []
  model_path: ''
  results_dir: ''
  backend_kwargs: {}
