# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/yolo_v3/proto/yolov3_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6nvidia_tao_deploy/cv/yolo_v3/proto/yolov3_config.proto\"\xca\x02\n\x0cYOLOv3Config\x12\x18\n\x10\x62ig_anchor_shape\x18\x01 \x01(\t\x12\x18\n\x10mid_anchor_shape\x18\x02 \x01(\t\x12\x1a\n\x12small_anchor_shape\x18\x03 \x01(\t\x12 \n\x18matching_neutral_box_iou\x18\x04 \x01(\x02\x12\x0c\n\x04\x61rch\x18\x05 \x01(\t\x12\x0f\n\x07nlayers\x18\x06 \x01(\r\x12\x18\n\x10\x61rch_conv_blocks\x18\x07 \x01(\r\x12\x17\n\x0floss_loc_weight\x18\x08 \x01(\x02\x12\x1c\n\x14loss_neg_obj_weights\x18\t \x01(\x02\x12\x1a\n\x12loss_class_weights\x18\n \x01(\x02\x12\x15\n\rfreeze_blocks\x18\x0b \x03(\x02\x12\x11\n\tfreeze_bn\x18\x0c \x01(\x08\x12\x12\n\nforce_relu\x18\r \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.yolo_v3.proto.yolov3_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _YOLOV3CONFIG._serialized_start=59
  _YOLOV3CONFIG._serialized_end=389
# @@protoc_insertion_point(module_scope)
