results_dir: "???"
dataset:
  label_map: "???"
  contiguous_id: True
  val:
    annotations: "???"
    images: "???"
    panoptic: "???"
    batch_size: 1
    num_workers: 2
  test:
    images: "???"
    batch_size: 1
export:
  task: "semantic"
model:
  test:
    object_mask_threshold: 0.5
    overlap_threshold: 0.8
  sem_seg_head:
    norm: "GN"
    num_classes: 133
inference:
  trt_engine: "???"
evaluate:
  trt_engine: "???"