# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/classification_tf1/proto/optimizer_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDnvidia_tao_deploy/cv/classification_tf1/proto/optimizer_config.proto\"S\n\x12SgdOptimizerConfig\x12\n\n\x02lr\x18\x01 \x01(\x02\x12\r\n\x05\x64\x65\x63\x61y\x18\x02 \x01(\x02\x12\x10\n\x08momentum\x18\x03 \x01(\x02\x12\x10\n\x08nesterov\x18\x04 \x01(\x08\"a\n\x13\x41\x64\x61mOptimizerConfig\x12\n\n\x02lr\x18\x01 \x01(\x02\x12\x0e\n\x06\x62\x65ta_1\x18\x02 \x01(\x02\x12\x0e\n\x06\x62\x65ta_2\x18\x03 \x01(\x02\x12\x0f\n\x07\x65psilon\x18\x04 \x01(\x02\x12\r\n\x05\x64\x65\x63\x61y\x18\x05 \x01(\x02\"Q\n\x16RmspropOptimizerConfig\x12\n\n\x02lr\x18\x01 \x01(\x02\x12\x0b\n\x03rho\x18\x02 \x01(\x02\x12\x0f\n\x07\x65psilon\x18\x03 \x01(\x02\x12\r\n\x05\x64\x65\x63\x61y\x18\x04 \x01(\x02\"\x90\x01\n\x0fOptimizerConfig\x12\"\n\x03sgd\x18\x01 \x01(\x0b\x32\x13.SgdOptimizerConfigH\x00\x12$\n\x04\x61\x64\x61m\x18\x02 \x01(\x0b\x32\x14.AdamOptimizerConfigH\x00\x12*\n\x07rmsprop\x18\x03 \x01(\x0b\x32\x17.RmspropOptimizerConfigH\x00\x42\x07\n\x05optimb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.classification_tf1.proto.optimizer_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SGDOPTIMIZERCONFIG._serialized_start=72
  _SGDOPTIMIZERCONFIG._serialized_end=155
  _ADAMOPTIMIZERCONFIG._serialized_start=157
  _ADAMOPTIMIZERCONFIG._serialized_end=254
  _RMSPROPOPTIMIZERCONFIG._serialized_start=256
  _RMSPROPOPTIMIZERCONFIG._serialized_end=337
  _OPTIMIZERCONFIG._serialized_start=340
  _OPTIMIZERCONFIG._serialized_end=484
# @@protoc_insertion_point(module_scope)
