# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/classification_tf1/proto/train_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_tao_deploy.cv.classification_tf1.proto import visualizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_visualizer__config__pb2
from nvidia_tao_deploy.cv.classification_tf1.proto import lr_config_pb2 as nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_lr__config__pb2
from nvidia_tao_deploy.cv.classification_tf1.proto import optimizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_optimizer__config__pb2
from nvidia_tao_deploy.cv.classification_tf1.proto import regularizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_regularizer__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nvidia_tao_deploy/cv/classification_tf1/proto/train_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n@nvidia_tao_deploy/cv/classification_tf1/proto/train_config.proto\x1a\x45nvidia_tao_deploy/cv/classification_tf1/proto/visualizer_config.proto\x1a=nvidia_tao_deploy/cv/classification_tf1/proto/lr_config.proto\x1a\x44nvidia_tao_deploy/cv/classification_tf1/proto/optimizer_config.proto\x1a\x46nvidia_tao_deploy/cv/classification_tf1/proto/regularizer_config.proto\"\x83\x05\n\x0bTrainConfig\x12\x1a\n\x12train_dataset_path\x18\x01 \x01(\t\x12\x18\n\x10val_dataset_path\x18\x02 \x01(\t\x12\x1d\n\x15pretrained_model_path\x18\x03 \x01(\t\x12#\n\toptimizer\x18\x04 \x01(\x0b\x32\x10.OptimizerConfig\x12\x1a\n\x12\x62\x61tch_size_per_gpu\x18\x05 \x01(\r\x12\x10\n\x08n_epochs\x18\x06 \x01(\r\x12\x11\n\tn_workers\x18\x07 \x01(\r\x12\x1e\n\nreg_config\x18\x08 \x01(\x0b\x32\n.RegConfig\x12\x1c\n\tlr_config\x18\t \x01(\x0b\x32\t.LRConfig\x12\x13\n\x0brandom_seed\x18\n \x01(\r\x12\x1a\n\x12\x65nable_random_crop\x18\x0b \x01(\x08\x12\x1a\n\x12\x65nable_center_crop\x18\x0e \x01(\x08\x12!\n\x19\x65nable_color_augmentation\x18\x0f \x01(\x08\x12\x17\n\x0flabel_smoothing\x18\x0c \x01(\x02\x12\x17\n\x0fpreprocess_mode\x18\r \x01(\t\x12\x13\n\x0bmixup_alpha\x18\x10 \x01(\x02\x12\x19\n\x11model_parallelism\x18\x11 \x03(\x02\x12/\n\nimage_mean\x18\x12 \x03(\x0b\x32\x1b.TrainConfig.ImageMeanEntry\x12\x1f\n\x17\x64isable_horizontal_flip\x18\x13 \x01(\x08\x12%\n\nvisualizer\x18\x14 \x01(\x0b\x32\x11.VisualizerConfig\x1a\x30\n\x0eImageMeanEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_visualizer__config__pb2.DESCRIPTOR,nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_lr__config__pb2.DESCRIPTOR,nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_optimizer__config__pb2.DESCRIPTOR,nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_regularizer__config__pb2.DESCRIPTOR,])




_TRAINCONFIG_IMAGEMEANENTRY = _descriptor.Descriptor(
  name='ImageMeanEntry',
  full_name='TrainConfig.ImageMeanEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TrainConfig.ImageMeanEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TrainConfig.ImageMeanEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=940,
  serialized_end=988,
)

_TRAINCONFIG = _descriptor.Descriptor(
  name='TrainConfig',
  full_name='TrainConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_dataset_path', full_name='TrainConfig.train_dataset_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_dataset_path', full_name='TrainConfig.val_dataset_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pretrained_model_path', full_name='TrainConfig.pretrained_model_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='optimizer', full_name='TrainConfig.optimizer', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size_per_gpu', full_name='TrainConfig.batch_size_per_gpu', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_epochs', full_name='TrainConfig.n_epochs', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_workers', full_name='TrainConfig.n_workers', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reg_config', full_name='TrainConfig.reg_config', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lr_config', full_name='TrainConfig.lr_config', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_seed', full_name='TrainConfig.random_seed', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_random_crop', full_name='TrainConfig.enable_random_crop', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_center_crop', full_name='TrainConfig.enable_center_crop', index=11,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_color_augmentation', full_name='TrainConfig.enable_color_augmentation', index=12,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_smoothing', full_name='TrainConfig.label_smoothing', index=13,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preprocess_mode', full_name='TrainConfig.preprocess_mode', index=14,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mixup_alpha', full_name='TrainConfig.mixup_alpha', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_parallelism', full_name='TrainConfig.model_parallelism', index=16,
      number=17, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_mean', full_name='TrainConfig.image_mean', index=17,
      number=18, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disable_horizontal_flip', full_name='TrainConfig.disable_horizontal_flip', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visualizer', full_name='TrainConfig.visualizer', index=19,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRAINCONFIG_IMAGEMEANENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=988,
)

_TRAINCONFIG_IMAGEMEANENTRY.containing_type = _TRAINCONFIG
_TRAINCONFIG.fields_by_name['optimizer'].message_type = nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_optimizer__config__pb2._OPTIMIZERCONFIG
_TRAINCONFIG.fields_by_name['reg_config'].message_type = nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_regularizer__config__pb2._REGCONFIG
_TRAINCONFIG.fields_by_name['lr_config'].message_type = nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_lr__config__pb2._LRCONFIG
_TRAINCONFIG.fields_by_name['image_mean'].message_type = _TRAINCONFIG_IMAGEMEANENTRY
_TRAINCONFIG.fields_by_name['visualizer'].message_type = nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_visualizer__config__pb2._VISUALIZERCONFIG
DESCRIPTOR.message_types_by_name['TrainConfig'] = _TRAINCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainConfig = _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), dict(

  ImageMeanEntry = _reflection.GeneratedProtocolMessageType('ImageMeanEntry', (_message.Message,), dict(
    DESCRIPTOR = _TRAINCONFIG_IMAGEMEANENTRY,
    __module__ = 'nvidia_tao_deploy.cv.classification_tf1.proto.train_config_pb2'
    # @@protoc_insertion_point(class_scope:TrainConfig.ImageMeanEntry)
    ))
  ,
  DESCRIPTOR = _TRAINCONFIG,
  __module__ = 'nvidia_tao_deploy.cv.classification_tf1.proto.train_config_pb2'
  # @@protoc_insertion_point(class_scope:TrainConfig)
  ))
_sym_db.RegisterMessage(TrainConfig)
_sym_db.RegisterMessage(TrainConfig.ImageMeanEntry)


_TRAINCONFIG_IMAGEMEANENTRY._options = None
# @@protoc_insertion_point(module_scope)
