# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/classification_tf1/proto/train_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_tao_deploy.cv.classification_tf1.proto import visualizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_visualizer__config__pb2
from nvidia_tao_deploy.cv.classification_tf1.proto import lr_config_pb2 as nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_lr__config__pb2
from nvidia_tao_deploy.cv.classification_tf1.proto import optimizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_optimizer__config__pb2
from nvidia_tao_deploy.cv.classification_tf1.proto import regularizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_classification__tf1_dot_proto_dot_regularizer__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@nvidia_tao_deploy/cv/classification_tf1/proto/train_config.proto\x1a\x45nvidia_tao_deploy/cv/classification_tf1/proto/visualizer_config.proto\x1a=nvidia_tao_deploy/cv/classification_tf1/proto/lr_config.proto\x1a\x44nvidia_tao_deploy/cv/classification_tf1/proto/optimizer_config.proto\x1a\x46nvidia_tao_deploy/cv/classification_tf1/proto/regularizer_config.proto\"\x83\x05\n\x0bTrainConfig\x12\x1a\n\x12train_dataset_path\x18\x01 \x01(\t\x12\x18\n\x10val_dataset_path\x18\x02 \x01(\t\x12\x1d\n\x15pretrained_model_path\x18\x03 \x01(\t\x12#\n\toptimizer\x18\x04 \x01(\x0b\x32\x10.OptimizerConfig\x12\x1a\n\x12\x62\x61tch_size_per_gpu\x18\x05 \x01(\r\x12\x10\n\x08n_epochs\x18\x06 \x01(\r\x12\x11\n\tn_workers\x18\x07 \x01(\r\x12\x1e\n\nreg_config\x18\x08 \x01(\x0b\x32\n.RegConfig\x12\x1c\n\tlr_config\x18\t \x01(\x0b\x32\t.LRConfig\x12\x13\n\x0brandom_seed\x18\n \x01(\r\x12\x1a\n\x12\x65nable_random_crop\x18\x0b \x01(\x08\x12\x1a\n\x12\x65nable_center_crop\x18\x0e \x01(\x08\x12!\n\x19\x65nable_color_augmentation\x18\x0f \x01(\x08\x12\x17\n\x0flabel_smoothing\x18\x0c \x01(\x02\x12\x17\n\x0fpreprocess_mode\x18\r \x01(\t\x12\x13\n\x0bmixup_alpha\x18\x10 \x01(\x02\x12\x19\n\x11model_parallelism\x18\x11 \x03(\x02\x12/\n\nimage_mean\x18\x12 \x03(\x0b\x32\x1b.TrainConfig.ImageMeanEntry\x12\x1f\n\x17\x64isable_horizontal_flip\x18\x13 \x01(\x08\x12%\n\nvisualizer\x18\x14 \x01(\x0b\x32\x11.VisualizerConfig\x1a\x30\n\x0eImageMeanEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.classification_tf1.proto.train_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAINCONFIG_IMAGEMEANENTRY._options = None
  _TRAINCONFIG_IMAGEMEANENTRY._serialized_options = b'8\001'
  _TRAINCONFIG._serialized_start=345
  _TRAINCONFIG._serialized_end=988
  _TRAINCONFIG_IMAGEMEANENTRY._serialized_start=940
  _TRAINCONFIG_IMAGEMEANENTRY._serialized_end=988
# @@protoc_insertion_point(module_scope)
