# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/common/proto/class_weighting_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>nvidia_tao_deploy/cv/common/proto/class_weighting_config.proto\"\xa6\x01\n\x14\x43lassWeightingConfig\x12\x42\n\x0f\x63lass_weighting\x18\x01 \x03(\x0b\x32).ClassWeightingConfig.ClassWeightingEntry\x12\x13\n\x0b\x65nable_auto\x18\x02 \x01(\x08\x1a\x35\n\x13\x43lassWeightingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.common.proto.class_weighting_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLASSWEIGHTINGCONFIG_CLASSWEIGHTINGENTRY._options = None
  _CLASSWEIGHTINGCONFIG_CLASSWEIGHTINGENTRY._serialized_options = b'8\001'
  _CLASSWEIGHTINGCONFIG._serialized_start=67
  _CLASSWEIGHTINGCONFIG._serialized_end=233
  _CLASSWEIGHTINGCONFIG_CLASSWEIGHTINGENTRY._serialized_start=180
  _CLASSWEIGHTINGCONFIG_CLASSWEIGHTINGENTRY._serialized_end=233
# @@protoc_insertion_point(module_scope)
