# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/common/proto/clearml_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6nvidia_tao_deploy/cv/common/proto/clearml_config.proto\"\x8b\x01\n\rClearMLConfig\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12\x1a\n\x12reuse_last_task_id\x18\x04 \x01(\x08\x12\x1a\n\x12\x63ontinue_last_task\x18\x05 \x01(\x08\x12\x15\n\rdeferred_init\x18\x06 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.common.proto.clearml_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLEARMLCONFIG._serialized_start=59
  _CLEARMLCONFIG._serialized_end=198
# @@protoc_insertion_point(module_scope)
