# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/common/proto/clearml_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nvidia_tao_deploy/cv/common/proto/clearml_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n6nvidia_tao_deploy/cv/common/proto/clearml_config.proto\"\x8b\x01\n\rClearMLConfig\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12\x1a\n\x12reuse_last_task_id\x18\x04 \x01(\x08\x12\x1a\n\x12\x63ontinue_last_task\x18\x05 \x01(\x08\x12\x15\n\rdeferred_init\x18\x06 \x01(\x08\x62\x06proto3')
)




_CLEARMLCONFIG = _descriptor.Descriptor(
  name='ClearMLConfig',
  full_name='ClearMLConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='ClearMLConfig.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task', full_name='ClearMLConfig.task', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='ClearMLConfig.tags', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reuse_last_task_id', full_name='ClearMLConfig.reuse_last_task_id', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='continue_last_task', full_name='ClearMLConfig.continue_last_task', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deferred_init', full_name='ClearMLConfig.deferred_init', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['ClearMLConfig'] = _CLEARMLCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClearMLConfig = _reflection.GeneratedProtocolMessageType('ClearMLConfig', (_message.Message,), dict(
  DESCRIPTOR = _CLEARMLCONFIG,
  __module__ = 'nvidia_tao_deploy.cv.common.proto.clearml_config_pb2'
  # @@protoc_insertion_point(class_scope:ClearMLConfig)
  ))
_sym_db.RegisterMessage(ClearMLConfig)


# @@protoc_insertion_point(module_scope)
