# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/common/proto/learning_rate_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_tao_deploy.cv.common.proto import soft_start_annealing_schedule_config_pb2 as nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_soft__start__annealing__schedule__config__pb2
from nvidia_tao_deploy.cv.common.proto import soft_start_cosine_annealing_schedule_config_pb2 as nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_soft__start__cosine__annealing__schedule__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nvidia_tao_deploy/cv/common/proto/learning_rate_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n<nvidia_tao_deploy/cv/common/proto/learning_rate_config.proto\x1aLnvidia_tao_deploy/cv/common/proto/soft_start_annealing_schedule_config.proto\x1aSnvidia_tao_deploy/cv/common/proto/soft_start_cosine_annealing_schedule_config.proto\"\xca\x01\n\x12LearningRateConfig\x12J\n\x1dsoft_start_annealing_schedule\x18\x01 \x01(\x0b\x32!.SoftStartAnnealingScheduleConfigH\x00\x12W\n$soft_start_cosine_annealing_schedule\x18\x02 \x01(\x0b\x32\'.SoftStartCosineAnnealingScheduleConfigH\x00\x42\x0f\n\rlearning_rateb\x06proto3')
  ,
  dependencies=[nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_soft__start__annealing__schedule__config__pb2.DESCRIPTOR,nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_soft__start__cosine__annealing__schedule__config__pb2.DESCRIPTOR,])




_LEARNINGRATECONFIG = _descriptor.Descriptor(
  name='LearningRateConfig',
  full_name='LearningRateConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='soft_start_annealing_schedule', full_name='LearningRateConfig.soft_start_annealing_schedule', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='soft_start_cosine_annealing_schedule', full_name='LearningRateConfig.soft_start_cosine_annealing_schedule', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='learning_rate', full_name='LearningRateConfig.learning_rate',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=228,
  serialized_end=430,
)

_LEARNINGRATECONFIG.fields_by_name['soft_start_annealing_schedule'].message_type = nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_soft__start__annealing__schedule__config__pb2._SOFTSTARTANNEALINGSCHEDULECONFIG
_LEARNINGRATECONFIG.fields_by_name['soft_start_cosine_annealing_schedule'].message_type = nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_soft__start__cosine__annealing__schedule__config__pb2._SOFTSTARTCOSINEANNEALINGSCHEDULECONFIG
_LEARNINGRATECONFIG.oneofs_by_name['learning_rate'].fields.append(
  _LEARNINGRATECONFIG.fields_by_name['soft_start_annealing_schedule'])
_LEARNINGRATECONFIG.fields_by_name['soft_start_annealing_schedule'].containing_oneof = _LEARNINGRATECONFIG.oneofs_by_name['learning_rate']
_LEARNINGRATECONFIG.oneofs_by_name['learning_rate'].fields.append(
  _LEARNINGRATECONFIG.fields_by_name['soft_start_cosine_annealing_schedule'])
_LEARNINGRATECONFIG.fields_by_name['soft_start_cosine_annealing_schedule'].containing_oneof = _LEARNINGRATECONFIG.oneofs_by_name['learning_rate']
DESCRIPTOR.message_types_by_name['LearningRateConfig'] = _LEARNINGRATECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LearningRateConfig = _reflection.GeneratedProtocolMessageType('LearningRateConfig', (_message.Message,), dict(
  DESCRIPTOR = _LEARNINGRATECONFIG,
  __module__ = 'nvidia_tao_deploy.cv.common.proto.learning_rate_config_pb2'
  # @@protoc_insertion_point(class_scope:LearningRateConfig)
  ))
_sym_db.RegisterMessage(LearningRateConfig)


# @@protoc_insertion_point(module_scope)
