# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/common/proto/optimizer_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia_tao_deploy.cv.common.proto import sgd_optimizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_sgd__optimizer__config__pb2
from nvidia_tao_deploy.cv.common.proto import adam_optimizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_adam__optimizer__config__pb2
from nvidia_tao_deploy.cv.common.proto import rmsprop_optimizer_config_pb2 as nvidia__tao__deploy_dot_cv_dot_common_dot_proto_dot_rmsprop__optimizer__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8nvidia_tao_deploy/cv/common/proto/optimizer_config.proto\x1a<nvidia_tao_deploy/cv/common/proto/sgd_optimizer_config.proto\x1a=nvidia_tao_deploy/cv/common/proto/adam_optimizer_config.proto\x1a@nvidia_tao_deploy/cv/common/proto/rmsprop_optimizer_config.proto\"\x94\x01\n\x0fOptimizerConfig\x12$\n\x04\x61\x64\x61m\x18\x01 \x01(\x0b\x32\x14.AdamOptimizerConfigH\x00\x12\"\n\x03sgd\x18\x02 \x01(\x0b\x32\x13.SGDOptimizerConfigH\x00\x12*\n\x07rmsprop\x18\x03 \x01(\x0b\x32\x17.RMSpropOptimizerConfigH\x00\x42\x0b\n\toptimizerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.common.proto.optimizer_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTIMIZERCONFIG._serialized_start=252
  _OPTIMIZERCONFIG._serialized_end=400
# @@protoc_insertion_point(module_scope)
