# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvidia_tao_deploy/cv/common/proto/sgd_optimizer_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<nvidia_tao_deploy/cv/common/proto/sgd_optimizer_config.proto\"8\n\x12SGDOptimizerConfig\x12\x10\n\x08momentum\x18\x01 \x01(\x02\x12\x10\n\x08nesterov\x18\x02 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia_tao_deploy.cv.common.proto.sgd_optimizer_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SGDOPTIMIZERCONFIG._serialized_start=64
  _SGDOPTIMIZERCONFIG._serialized_end=120
# @@protoc_insertion_point(module_scope)
