results_dir: "??"
encryption_key: nvidia_tao
model:
  TPS: False
  backbone: ResNet
  feature_channel: 512
  sequence: BiLSTM
  hidden_size: 256
  prediction: CTC
dataset:
  train_dataset_dir: ["??"]
  val_dataset_dir: "??"
  character_list_file: "??"
  input_width: 100
  input_height: 32
  input_channel: 1
  max_label_length: 25
  batch_size: 32
  workers: 4
  augmentation:
    keep_aspect_ratio: False
train:
  seed: 1111
  gpu_ids: [0]
  optim:
    name: "adadelta"
    lr: 1.0
  clip_grad_norm: 5.0
  num_epochs: 12
  checkpoint_interval: 1
  validation_interval: 1
evaluate:
  gpu_ids: [0]
  checkpoint: "??"
  test_dataset_dir: "??"
inference:
  gpu_ids: [0]
  checkpoint: "??"
  inference_dataset_dir: "??"
export:
  gpu_id: 0
  checkpoint: "??"
prune:
  gpu_id: 0
  checkpoint: "??"
  results_dir: "${results_dir}/prune"
  prune_setting:
    mode: amount
    amount: 0.4
    granularity: 8
    raw_prune_score: L1
dataset_convert:
  input_img_dir: "??"
  gt_file: "??"
  results_dir: "${results_dir}/convert_dataset"
gen_trt_engine:
  onnx_file: "??"
